language: go
go:
- 1.12.5
os:
- linux
dist: trusty
sudo: false
install: true
script:
- env GO111MODULE=on go build
- env GO111MODULE=on go test
notifications:
  slack:
    on_failure: always
    on_success: always
    secure: HXTlbNhTp3k91CXm8uh3s2tfCF1DKsUOjlVpzZS7o5CjTQcWqNTMaJqZE8SLO83LzHD6eVE2+oHeUXaEDDFcddm/+6uQ82x9m7NwBcGW6OqyBD7OLq8tIiWs0gaYeubCZ/cQVUeQHYwJHVC/xNMYRisojlVrNxxnbCQ+6BwzenpJk7LRPsHfW2o9j89ApnHceAroRRcSYgdL/orGZvJ5AuiA90OAQXkpi3f1BNFNP9X7TckkoziZ1hnKudwvYdisiPogCjxEvb2EZwg/sPMk5wOSehx7YImNEGDeoSrToAISM8NtXL7ODJwRcPndkCDJGxhhnbl9Zt+59ZyL0bQyxTayAqagVYecihyf38uss27T84BAN/gUO+H6yyEykpuPLa9AvgQDjHZhagmLOksYetfdOb3ZGniUohdJeVU2b/NN9esJp6xeUaVqhJmicbOQrwIHrtqkIHrgxLgGyBfhAPWLW7bkeoa73bN5LwhQrefVIDbuBZYajDGLMn+U0eRjN2FAGwOBNEDc7WhDEH89PSve4zAUMR8nOqml9MOZQC0b35pecLplVg6bMh0cbIjjLYL68KsbGNugdIpkVTUbZODgUZQnG9P+DVPUX72kgmA2XjjLkDP1iXtK/bC40y55w2IzG/Po/vO5j0fGUwz+uNKRaEPISKdx6Lp7GDq3AW0=
