#!/bin/sh

## Definition
compile () {  
  # Please write an compile command here
  # The file name must be "Main + extension"
  # If you do not need compilation please return 0.
  return 0
}

execute () {
  # Please write an execution command here
  # The file name to execute is "Main + extension"
  # If it is a binary file, no extension is required.
  return 0
}


## Execute
compile

input_dir="./input/"
output_dir="./output/"

if [ ! -d $input_dir ]; then
  echo "Input dir not found"
  exit 1
fi

if [ ! -d $output_dir ]; then
  mkdir $output_dir
fi

for file in `ls ${input_dir}`; do
  out_file_name=`echo $file | cut -d "." -f 1`
  execute < "$input_dir$file" > "$output_dir$out_file_name.out"
done
